server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: asscache
          uri: lb://ASSCACHE
          predicates:
            - Path=/asscache/**
          filters:
            - RewritePath=/asscache/(?<segment>.*), /$\{segment}
        - id: scaa
          uri: lb://SCAA
          predicates:
            - Path=/scaa/**
          filters:
            - RewritePath=/scaa/(?<segment>.*), /$\{segment}
        - id: nameserver
          uri: lb://NAMESERVER
          predicates:
            - Path=/nameserver/**
          filters:
            - RewritePath=/nameserver/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true