services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - scaa-network
  asscache:
    build: asscache
    image: asscache
    ports:
      - "8000"
    depends_on:
      - gateway
      - rabbitmq
    networks:
      - scaa-network
  gateway:
    build: gateway
    image: gateway
    ports:
      - "8765:8765"
    depends_on:
      - nameserver
    networks:
      - scaa-network
  nameserver:
    build: nameserver
    image: nameserver
    ports:
      - "8761:8761"
    networks:
      - scaa-network
  scaa:
    build: scaa
    image: scaa
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - gateway
    networks:
      - scaa-network
    volumes:
      - ./scaa/src/main/resources:/app/src/main/resources
networks:
  scaa-network: